FROM ubuntu:22.04

ARG ROOT_PASS=root
ENV DEBIAN_FRONTEND=noninteractive 

# TODO Nginx here may be dropped here in favor of some small python library
RUN apt-get update && \
  apt-get install \
  software-properties-common \
  git \
  pip \
  clang-14 \
  lsb-release \
  cmake \
  nginx \
  curl \
  vim \
  -y
RUN ln -s /usr/bin/clang-14 /usr/local/bin/clang && \
  ln -s /usr/bin/clang++-14 /usr/local/bin/clang++
RUN pip install conan --quiet

# Gists
ADD https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/create-env-example.sh \
  /scripts/create-env-example.sh
ADD https://gist.githubusercontent.com/utkusarioglu/3523b00578807d63b05399fe57a4b2a7/raw/.bashrc \
  /root/.bashrc
ADD https://gist.githubusercontent.com/utkusarioglu/d5c216c744460c45bf6260d0de4131b4/raw/.inputrc \
  /root/.inputrc
RUN chmod +x \
  /scripts/create-env-example.sh \
  /root/.bashrc \
  /root/.inputrc

RUN echo "root:$ROOT_PASS" | chpasswd
