name: Push

on:
  push

jobs:
  push:
    uses: ./.github/workflows/build.wfc.yml
    with:
      # Named after clang version
      # image_tag: 14-3.13-ubuntu-test-27
      image_tag: 20-3.13-ubuntu-test-27

      # https://hub.docker.com/repository/docker/utkusarioglu/ubuntu-devcontainer/tags
      # base_tag: 23-ubuntu-test-24
      base_tag: 2404-test-21
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
